<a href="https://colab.research.google.com/github/SauravDakre/MachineLearning/blob/master/basics/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# NumPy Arrays


`np.array` takes python list and dtype (numpy type) as input.  
refer ex of 1-D matrix



In [2]:
arr = np.array([0,1,2], dtype=np.float32)
arr

array([0., 1., 2.], dtype=float32)

repr() function returns a printable representation string of given object

In [4]:
repr(arr)

'array([0., 1., 2.], dtype=float32)'

In [5]:
print(repr(arr))

array([0., 1., 2.], dtype=float32)


example to create 2D matrix

In [8]:
arr = np.array([[0,1,2], [3,4,5]], dtype=np.float32)
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

## Copying

In [10]:
a = np.array([0,2])
b = np.array([1,5])
print('a: {}'.format(repr(a)))
print('b: {}'.format(repr(b)))
c=a
d = b.copy()
c[0]=5
d[0]=6
print('a: {}'.format(repr(a)))
print('b: {}'.format(repr(b)))

a: array([0, 2])
b: array([1, 5])
a: array([5, 2])
b: array([1, 5])


## Casting

In [11]:
a = np.array([0,2])
print(a.dtype , a)
a = a.astype(np.float32)
print(a.dtype , a)

int64 [0 2]
float32 [0. 2.]


## NaN

In [15]:
a = np.array([np.nan, 1,2])
b = np.array([np.nan, 'a'])

# c = np.array([np.nan, 1], dtype=np.int32) # ValueError: cannot convert float NaN to integer
print('a', a.dtype, a)
print('b', b.dtype, b)

a float64 [nan  1.  2.]
b <U32 ['nan' 'a']


## infinity

In [17]:
print(np.inf > 100000000000)
a = np.array([np.inf, 5, -np.inf])
print(repr(a))
# np.array([np.inf, 5, -np.inf], dtype=np.int32) # OverflowError: cannot convert float infinity to integer

True
array([ inf,   5., -inf])


In [19]:
float_arr = np.array([1,5.4, 3])
print(float_arr.dtype, repr(float_arr))

float64 array([1. , 5.4, 3. ])


# Basics

## ranged data

In [23]:
a = np.arange(2)
b = np.arange(-1,3)
c = np.arange(2,15,4)
print(a)
print(b)
print(c)

[0 1]
[-1  0  1  2]
[ 2  6 10 14]


In [24]:
a = np.linspace(2,15,num=4)
b = np.linspace(2,15,num=4,endpoint=False)
c = np.linspace(2,15,num=4,endpoint=False, dtype=np.int32)
print(a)
print(b)
print(c)

[ 2.          6.33333333 10.66666667 15.        ]
[ 2.    5.25  8.5  11.75]
[ 2  5  8 11]


## reshape

In [26]:
ar = np.arange(10)
print(ar.dtype, ar)

int64 [0 1 2 3 4 5 6 7 8 9]


In [31]:
# r1 = np.reshape(ar, (2,4)) # ValueError: cannot reshape array of size 10 into shape (2,4)
r2 = np.reshape(ar, (2,5))
print( r2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [35]:
ar = np.arange(12)
r2 = np.reshape(ar, (2,-1,2)) # the special value of -1 can be used in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.
print(r2.shape, r2)

(2, 3, 2) [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [37]:
f1 = r2.flatten()
print(f1.shape, f1)

(12,) [ 0  1  2  3  4  5  6  7  8  9 10 11]


## transpose

In [39]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(arr.shape, arr)
print(transposed.shape, transposed)

(4, 2) [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(2, 4) [[0 2 4 6]
 [1 3 5 7]]


In [41]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
print(arr)
transposed = np.transpose(arr, axes=(1, 2, 0))
print(transposed)
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  8 16]
  [ 1  9 17]]

 [[ 2 10 18]
  [ 3 11 19]]

 [[ 4 12 20]
  [ 5 13 21]]

 [[ 6 14 22]
  [ 7 15 23]]]
arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


In [45]:
a = np.zeros(4)
print(a)
b = np.ones((2,4), dtype=np.int32)
print(b)
c=np.zeros_like(b)
print(c)
a = np.array([[1,2], [3,4]])
print(a)
b = np.ones_like(a)
print(b)


[0. 0. 0. 0.]
[[1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
